=== TIBHannover/oersi-etl/src/main/resources/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "resource:/schemas/schema.json",
  "title": "OER",
  "description": "This is a generic JSON schema for describing an Open Educational Resource with schema.org. This is a stricter but compatible version of the LRMI schema (https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schema.json)",
  "type": "object",
  "properties": {
    "@context": {
      "$ref": "resource:/schemas/context-schema.json"
    },
    "id": {
      "$ref": "resource:/schemas/id.json"
    },
    "type": {
      "$ref": "resource:/schemas/type.json"
    },
    "name": {
      "$ref": "resource:/schemas/name.json"
    },
    "creator": {
      "$ref": "resource:/creator.json"
    },
    "contributor": {
      "$ref": "resource:/contributor.json"
    },
    "description": {
      "$ref": "resource:/description.json"
    },
    "about": {
      "$ref": "resource:/about.json"
    },
    "license": {
      "$ref": "resource:/license.json"
    },
    "image": {
      "$ref": "resource:/image.json"
    },
    "dateCreated": {
      "$ref": "resource:/dateCreated.json"
    },
    "inLanguage": {
      "$ref": "resource:/inLanguage.json"
    },
    "publisher": {
      "$ref": "resource:/publisher.json"
    },
    "learningResourceType": {
      "$ref": "resource:/learningResourceType.json"
    },
    "audience": {
      "$ref": "resource:/audience.json"
    },
    "isBasedOn": {
      "$ref": "resource:/isBasedOn.json"
    },
    "isPartOf": {
      "$ref": "resource:/isPartOf.json"
    },
    "hasPart": {
      "$ref": "resource:/hasPart.json"
    },
    "mainEntityOfPage": {
      "$ref": "resource:/mainEntityOfPage.json"
    },
    "keywords": {
      "$ref": "resource:/keywords.json"
    }
  },
  "required": [
    "@context",
    "id",
    "name",
    "type",
    "mainEntityOfPage"
  ]
}

=== TIBHannover/oersi-etl/data/experimental/orca/resources/oer:18.json
{"image":"https://example.org/oer/image.png","creator":[{"name":"HansD","type":"Person"}],"audience":[{"id":"http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student"}],"about":[{"id":"https://w3id.org/kim/hochschulfaechersystematik/n059"}],"description":"Eine OER","inLanguage":["fr"],"mainEntityOfPage":[{"dateCreated":"2020-01-01","provider":{"name":"ZOERR","id":"https://oerworldmap.org/resource/urn:uuid:4062c64d-b0ac-4941-95c2-8116f137326d"},"dateModified":"2021-08-20","id":"https://api.hoerkaen.hbz-nrw.de/resource/oer:18","type":"Text"}],"type":["LearningResource"],"@context":["https://w3id.org/kim/lrmi-profile/draft/context.jsonld",{"@language":"de"}],"license":{"id":"https://creativecommons.org/publicdomain/zero/1.0/"},"dateCreated":"2019-07-03","name":"Beispielressource","publisher":[{"name":"Tutory","id":"https://www.tutory.de","type":"Organization"}],"id":"https://example.org/oer"}

=== TIBHannover/oersi-etl/data/experimental/orca/resources/oer:19.json
{"creator":[{"name":"Jens Lechtenbörger","id":"https://orcid.org/0000-0002-3064-147X","type":"Person"}],"audience":[{"inScheme":{"id":"http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/"},"prefLabel":{"en":"student"},"id":"http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student","type":"Concept"}],"keywords":["Computer Science","Operation Systems","Computer Structures"],"hasPart":[{"name":"JiTT for OS","id":"https://oer.gitlab.io/OS/Operating-Systems-JiTT.html","type":["LearningResource","PresentationDigitalDocument"]},{"name":"OS Overview","id":"https://oer.gitlab.io/OS/Operating-Systems-Overview.html","type":["LearningResource","PresentationDigitalDocument"]},{"name":"OS Introduction","id":"https://oer.gitlab.io/OS/Operating-Systems-Introduction.html","type":["LearningResource","PresentationDigitalDocument"]},{"name":"OS02: Interrupts","id":"https://oer.gitlab.io/OS/Operating-Systems-Interrupts.html","type":["LearningResource","PresentationDigitalDocument"]},{"name":"OS08: Virtual Memory I","id":"https://oer.gitlab.io/OS/Operating-Systems-Memory-I.html","type":["LearningResource","PresentationDigitalDocument"]}],"about":[{"inScheme":{"id":"https://w3id.org/kim/hochschulfaechersystematik/scheme"},"prefLabel":{"de":"Informatik"},"id":"https://w3id.org/kim/hochschulfaechersystematik/n079","type":"Concept"}],"description":"A course on Operating Systems (following the book Operating Systems and Middleware: Supporting Controlled Interaction by Max Hailperin) as part of the module Computer Structures and Operating Systems for 4th-term students in the Bachelor program in Information Systems at the University of Münster, Germany.","inLanguage":["en"],"type":["LearningResource","Course"],"mainEntityOfPage":[{"dateCreated":"2021-08-20","id":"https://api.hoerkaen.hbz-nrw.de/resource/oer:19"}],"@context":["https://w3id.org/kim/lrmi-profile/draft/context.jsonld",{"@language":"de"}],"license":{"id":"https://creativecommons.org/licenses/by-sa/4.0/"},"name":"Computer Structures and Operating Systems","id":"https://oer.gitlab.io/OS"}
